version: "3.6"
services:
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    networks:
      - main-network
    volumes:
      - wordpress_vol22:/var/www/html/
    ports:
      - '443:443'
    depends_on:
      - wordpress
    restart: always

  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file:
      - .env
    networks:
      - main-network
    volumes:
      - mariadb_vol22:/var/lib/mysql/
    restart: always

  wordpress:
    depends_on:
      - mariadb
    image: wordpress
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    networks:
      - main-network
    volumes:
      - wordpress_vol22:/var/www/html/
    restart: always

  adminer:
    depends_on:
      - mariadb
    image: adminer
    build: ./requirements/bonus/adminer
    container_name: adminer
    networks:
      - main-network
    volumes:
      - wordpress_vol22:/var/www/html/
    restart: always

  ftp-server:
    build: ./requirements/bonus/ftp
    container_name: ftp-server
    image: ftp-server
    networks:
      - main-network
    volumes:
      - wordpress_vol22:/var/www/html/
    env_file:
      - .env
    ports:
      - '21:21'
    restart: always

  redis:
    depends_on:
      - wordpress
    networks:
      - main-network
    build: ./requirements/bonus/redis
    container_name: redis
    image: redis
    volumes:
      - wordpress_vol22:/var/www/html/
    restart: always

  node:
    build: ./requirements/bonus/node
    container_name: node
    image: node
    networks:
      - main-network
    ports:
      - '3001:3000'
    restart: always

  static_website:
    build: ./requirements/bonus/static_website
    container_name: static_website
    image: static_website
    # depends_on:
    #   - node
    networks:
      - main-network
    ports:
      - '8001:8001'
    restart: always

networks:
  main-network:
    driver: bridge

volumes:
    wordpress_vol22:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: "/home/aaitoual/data/wordpress_volume"
    mariadb_vol22:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: "/home/aaitoual/data/mariadb_volume"