version: "3.6"
services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - wordpress_vol:/var/www/html/
    ports:
      - '3000:80'
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_vol:/var/lib/mysql
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_vol:/var/www/html/
volumes:
  wordpress_vol:
  mariadb_vol:
