version: "3.6"
services:
  nginx:
    build: ./requirements/nginx
    container_name: nginx
    volumes:
      - wordpress_vol22:/var/www/html/
    ports:
      - '443:443'
    depends_on:
      - wordpress
  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_vol22:/var/lib/mysql/
  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    container_name: wordpress
    env_file:
      - .env
    volumes:
      - wordpress_vol22:/var/www/html/

  adminer:
    depends_on:
      - mariadb
    build: ./requirements/bonus/adminer
    container_name: adminer
    volumes:
      - wordpress_vol22:/var/www/html/
  ftp:
    build: ./requirements/bonus/ftp
    container_name: FTP
    volumes:
      - wordpress_vol22:/var/www/html/
    env_file:
      - .env
    ports:
      - '21:21'
  redis:
    depends_on:
      - wordpress
    build: ./requirements/bonus/redis
    container_name: redis
    volumes:
      - wordpress_vol22:/var/www/html/

  # static_website:
  #   build: ./requirements/bonus/static_website
  #   container_name: static_website
  #   ports:
  #     - '3000:3000'
volumes:
    wordpress_vol22:
    #     driver: local
    #     driver_opts:
    #         o: "bind"
    #         type: "none"
    #         device: "/Users/aaitoual/Desktop/data/wordpress/"
    mariadb_vol22:
        # driver: local
        # driver_opts:
        #     o: "bind"
        #     type: "none"
        #     device: "/Users/aaitoual/Desktop/data/mariadb/"