FROM debian:buster

# RUN apt update && apt upgrade

# RUN apt install nginx -y

# RUN apt install vim -y

# RUN apt install wget -y

# RUN apt install mariadb-server -y

# RUN service mysql start

# # RUN mysql_secure_installation

# RUN apt install php7.3 php7.3-cli php7.3-fpm php7.3-mysql php7.3-json php7.3-opcache php7.3-mbstring php7.3-xml php7.3-gd php7.3-curl -y

# RUN service start php7.3-fpm
